### ISSUE TITLE
seg剪枝怎么改啊还是是这样

### ISSUE THREAD

**Issue by yinheyu** [Cydia2018/YOLOv5-Light#5]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

       elif m is Segment:
            for j in range(3):
                ignore_idx.append(named_m_base + ".m.{}".format(j))
                from_to_map[named_m_base + ".m.{}".format(j)] = fromlayer[f[j]]
            for j in range(3):
                ignore_idx.append(named_m_base + ".proto.cv{}.conv".format(j))
                fromlayer.append(named_m_base + ".proto.cv{}.conv".format(j))

报错：
Traceback (most recent call last):
  File "D:\YOLOv5-Light-main\pruning\slim.py", line 115, in <module>
    prune_and_export(model, ignore_idx, opt)
  File "D:\YOLOv5-Light-main\pruning\slim.py", line 53, in prune_and_export
    weights_inheritance(model, compact_model, from_to_map, maskbndict)
  File "D:\YOLOv5-Light-main\utils\prune_utils.py", line 198, in weights_inheritance
    former = from_to_map[layername]
KeyError: 'model.24.proto.cv1.conv'

**Comment by yinheyu** [comment]
elif m is Segment:
              for j in range(3):
                  ignore_idx.append(named_m_base + ".proto.cv{}.conv".format(j))
                  from_to_map[named_m_base + ".proto.cv{}.conv".format(j)] = fromlayer[f[j]]


Traceback (most recent call last):
  File "D:\YOLOv5-Light-main\pruning\slim.py", line 115, in <module>
    prune_and_export(model, ignore_idx, opt)
  File "D:\YOLOv5-Light-main\pruning\slim.py", line 53, in prune_and_export
    weights_inheritance(model, compact_model, from_to_map, maskbndict)
  File "D:\YOLOv5-Light-main\utils\prune_utils.py", line 198, in weights_inheritance
    former = from_to_map[layername]
KeyError: 'model.24.m.0'
